### ISSUE TITLE
Error: Financial Type is Required (Joomla!)

### ISSUE THREAD

**Issue by philmb** [twomice/com.joineryhq.percentagepricesetfield#13]
First, I was excited to find your PercentagePriceSetField CiviCRM extension today! I’ve been looking for something like that, and I am eager to implement your code. Thanks for the work you put into that.

As I was saving my first percentage field, I received a "Financial Type is required" error, even though I have clearly included a Financial Type. See image.
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/7117661/20802386/7e70c1b2-b7b1-11e6-8646-13fc20a18efc.png)

I'm using CiviCRM 4.7.12 on Joomla 3.6.0. I appreciate any support you can provide.

**Comment by twomice** [comment]
It's odd that the "Price Field Options" list is still displaying when the "Field calculates 'automatic additional percentage'" field is checked -- those options are typically hidden in that case. I'm suspecting there's something specific to Joomla! here. I'll have to check on a Joomla! site and see if I can reproduce this.

**Comment by philmb** [comment]
Thanks for checking into it. Is there anything I can help with? I'm not a developer, but I'm a dabbler and eager to help such as I can.

**Comment by twomice** [comment]
Update: I've been able to reproduce this behavior in CiviCRM 4.7.12 on Joomla! 3.6.4. Hope to have a fix here soon.

**Comment by twomice** [comment]
Hi @philmb I've committed a fix in https://github.com/twomice/com.joineryhq.percentagepricesetfield/commit/8fd109d2e3284888c1ada52589e148f5353d7253 . Would you mind checking to see if it fixes the issue for you? Thanks!

(Re-openning, pending confirmation from @philmb.)

**Comment by philmb** [comment]
@twomice , I'm sorry to say that this didn't fix it for me. I tried saving a checkbox price field without selecting the "Automatic Additional Percentage" box, and it saved as normal. Then I edited the field, this time selecting the "AAP" box, and it gave the same "Financial type required" error as above.

**Comment by twomice** [comment]
Hi @philmb A few more questions for you:

1. In your original screenshot, the checkbox "Field calculates 'Automatic Additional Percentage'", and a couple of other related fields, is displayed at the top of the form, whereas it should be displayed within the form, below the "Input Field Type" field, as in this screenshot:
![percentage](https://cloud.githubusercontent.com/assets/759449/21461814/c88c480a-c91a-11e6-88bb-86b04688378a.png)

After applying the patch, are these fields still wrongly placed far at the top of the form?

2. Are there javascript errors on the page? (For example, in chrome: right-click anywhere on the page, click "Inspect" and observe the developer tools pane at the bottom of the page, then click the "Console" tab in that pane to see any Javascript errors. In firefox, try Ctrl + Shift + J to display the JavaScript console.)

Thanks!

**Comment by twomice** [comment]
@philmb If the above is working for you I'll commit it to the next release. But if not, please let me know and I'll be glad to help further.

**Comment by philmb** [comment]
Sorry, @twomice, this got lost in the holiday mess. With the patch, it is still displaying exactly as my original screenshot.

You are right about checking JS errors: 
JQMIGRATE: Migrate is installed, version 1.4.1
http://[domain]/media/civicrm/custom_ext/com.joineryhq.percentageprices…m.joineryhq.percentagepricesetfield-master/js/admin_price_field.js?r=IDsOl Failed to load resource: the server responded with a status of 403 (Forbidden)

Seeing this, I checked two things. 1) htaccess, which showed nothing that should affect access. 2) file permissions for the js/ directory. Both the directory and the two files within were set to owner access only. I played around with permissions, but the JS error remained even after granting public Read/Execute permission. Maybe I should check with our hosting service?

**Comment by philmb** [comment]
@twomice , Is there more work to be done on this bug? It's still not working for me, as per my above comment.

**Comment by twomice** [comment]
Hi @philmb I must have missed your response. Thanks for the details and for checking back.

Based on what you're reporting, it's clear that the relevant javacript file is not loading; the harder question is "why".  Here are some things you could check:

* In CiviCRM, visit Administer >> System Settings >> Resource URLs, and ensure that the "Extension Resource URL" setting is correct.  If you change it, it will change the URL for the javascript file (i.e., the file you reported as returning with a 403 in the JS errors above).
* If the file is still returning with a 403 error, you'll need to find out why the web server is begin denied access to that file. This can be fixed by correcting file permissions on directories in the file's path; more specific steps will depend on your site's configuration. 

From what I'm seeing in your description, it seems like this is a configuration issue with the "Extension Resource URL" setting, and/or with server file permissions, rather than a bug in the extension.  I can't provide detailed website support through this forum, but if you still get the impression it's caused by the extension, please post back here with your findings on the above and I'll be glad to help further.

**Comment by philmb** [comment]
Update: the problem was in fact a server permissions problem. My hosting service straightened it out: "The admin_price_field.js script and its folder had incorrect 700 permissions. We changed them to 755." I'm posting this for others who may have the same problem.

Thanks for your great extension and your patient assistance!

**Comment by twomice** [comment]
Thanks for the follow-up @philmb. Glad you got it worked out!
